# Generated by Django 3.2.7 on 2021-09-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('surename', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('fathername', models.CharField(blank=True, max_length=250, null=True, verbose_name='Отчество')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('birthday', models.DateField(verbose_name='День рождения')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('write_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='books/%y/%m/%d')),
                ('autor_relative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.autor', verbose_name='Автор произведения')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название магазина')),
                ('adress', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('assort', models.ManyToManyField(blank=True, null=True, related_name='assort_to_books', to='books.Books')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(max_length=250)),
                ('review', models.CharField(max_length=3000)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.books', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['nic'],
            },
        ),
    ]
