# Generated by Django 3.2.7 on 2021-11-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_statistdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistdata',
            name='save_books_name',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Книги, которые добавили в этот день'),
        ),
    ]
